### ISSUE TITLE
Eclipse IDE 2023-06: Upgrade Mylyn WikiText from 3.0.46 to 3.0.47

### ISSUE THREAD

**Issue by howlger** [eclipse-mylyn/org.eclipse.mylyn.docs#101]
Please upgrade [`mylyn-docs.aggrcon`](https://git.eclipse.org/c/simrel/org.eclipse.simrel.build.git/tree/mylyn-docs.aggrcon) from 3.0.46 to [3.0.47](https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs/releases/tag/wikitext.core-3.0.47) so that **Eclipse IDE 2023-06** will contain latest **Mylyn WikiText 3.0.47** version.

**Comment by akurtakov** [comment]
I have missed this notification (Sorry about that!) and can also appreciate some help on this one e.g. a gerrit like https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/203445 in addition to this issue so hopefully I don't miss it and it becomes a single click for me.
