### ISSUE TITLE
Is a new release planned for contribution to SimRel 2023-09?

### ISSUE THREAD

**Issue by merks** [eclipse-mylyn/org.eclipse.mylyn.docs#122]
It would be nice to eliminate this duplicate version of guava:

![image](https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs/assets/208716/47062c7d-6b91-4d04-8cb1-908e6bc4cc40)

I think the work is already done, but I can't find snapshot builds to verify that assumption.

(I'd use a discussion to ask the question but discussions aren't enabled for this repository.)

**Comment by akurtakov** [comment]
Snapshots are available at https://download.eclipse.org/mylyn/snapshots/nightly/docs/ .  @leods is the one that usually takes care of releases.

**Comment by akurtakov** [comment]
@ruspl-afed @wimjongman Would you please enable discussions for this repo ? Only PLs can do it.

**Comment by merks** [comment]
@akurtakov 

A PL needs to approve the PR, but anyone can create the PR to configure this:

https://github.com/eclipse-mylyn/.eclipsefdn/blob/main/otterdog/eclipse-mylyn.jsonnet

@leods 

RC1 is due by next Wednesday and then the final RC2 (release) the week after.   I tested that the snapshot aggregates without a problem, so it would be really great to have a release available for RC1 if at all possible.  I can help contribute it if that makes things easier.  Thanks in advance.

**Comment by akurtakov** [comment]
@merks Thanks, it's first time I hear about this jsonnet file.

**Comment by merks** [comment]
It's very cool.  I posted some helpful links here:

https://www.eclipse.org/lists/cross-project-issues-dev/msg19715.html

**Comment by ruspl-afed** [comment]
> @ruspl-afed @wimjongman Would you please enable discussions for this repo ? Only PLs can do it.

BTW, who is actual PL for Mylyn Docs project?

**Comment by wimjongman** [comment]
I think it is @akurtakov. Maybe best to start the PL process for him.

**Comment by merks** [comment]
Here is only one project, the Mylyn project, hence only one GitHub organization.  

This is what the project portal says:

https://projects.eclipse.org/projects/tools.mylyn/who

Mylyn Docs is just a GitHub repository, not project.

**Comment by wimjongman** [comment]
I think Alexander meant 'who is the de-facto project lead for Docs'

**Comment by merks** [comment]
It’s not a project but yes @akurtakov leads.   Of course he can be elected a Mylyn PL.   Someone might ask if 4 leads is a little much. 😳

**Comment by ruspl-afed** [comment]
> Someone might ask if 4 leads is a little much. 😳

Mylyn Docs is actually a different project with its own lifecycle. 
It had different set of [releases](https://projects.eclipse.org/projects/tools.mylyn) and TBH I have no idea when we should expect the next release of Mylyn Docs.

**Comment by merks** [comment]
I know the de facto details but unless it is a project with its own projects.eclipse.org ID then it’s not a project in the formal sense.  So it cannot have a formal project lead.  Just saying.   I’m not sure where this line of reasoning is headed.

**Comment by ruspl-afed** [comment]
Let's ask @waynebeaton regarding reasoning and shouldn't we have a dedicated project for Mylyn Docs. 
Because current situation is strange and may lead us to the state when Mylyn Docs is not ready for SimRel in time.

**Comment by merks** [comment]
I don’t think the current state has any impact on when/how Mylyn docs produces results for simrel.  It is a fact that it operates quite independently and that even its releases are independent so in that sense it already operates as a separate project.  Hopefully this doesn’t digress into namespace discussions. 😱

**Comment by BeckerFrank** [comment]
> @ruspl-afed @wimjongman Would you please enable discussions for this repo ? Only PLs can do it.

No you need to fill a Gitlab Help Desk Ticket to enable the discussions.

**Comment by merks** [comment]
> > @ruspl-afed @wimjongman Would you please enable discussions for this repo ? Only PLs can do it.
> 
> No you need to fill a Gitlab Help Desk Ticket to enable the discussions.

Not anymore.  Read https://www.eclipse.org/lists/cross-project-issues-dev/msg19715.html for the self serve details.

**Comment by wimjongman** [comment]
> If 4 PL is too much, I am willing to give up my PL role as long as I remain a committer.

Same for me.

**Comment by akurtakov** [comment]
And I am not eager to be a PL as I try to keep wikitext in shape but I hardly find time for releases so current status is just fine for me :).

**Comment by ruspl-afed** [comment]
I understand. 

So, what about _subj_?
Or, may be in a shorter form: is there a new release planned [for Mylyn Docs]?

**Comment by akurtakov** [comment]
I have a very tight schedule right now with Wed being last day before vacation thus I would appreciate if someone can do it . I'll try to find time myself but there are high chances to not be able to do it.

**Comment by akurtakov** [comment]
https://git.eclipse.org/r/c/simrel/org.eclipse.simrel.build/+/203915 delivered the just released version to simrel.

**Comment by waynebeaton** [comment]
> Let's ask @waynebeaton regarding reasoning and shouldn't we have a dedicated project for Mylyn Docs. Because current situation is strange and may lead us to the state when Mylyn Docs is not ready for SimRel in time.

Sorry, I missed this notification.

I have no strong opinion. Eclipse Mylyn Docs can be a separate Eclipse open source project, or it can be a separate GitHub project within the Eclipse Mylyn project, or you can merge it into a common GitHub project. In any configuration, docs can do releases that are synchronised or not with rest of the Eclipse Mylyn project. 

It's really up to the team to decide what to do.

**Comment by akurtakov** [comment]
Having a separate project will not change even a single bit how many people work on the project. It was a separate project a year ago, it is part of Mylyn now and before and now the problem who does releases and contributes them to simrel was there and is still around. With the above said I strongly believe that any change would be just time lost. If I have to change some releng again for project change I will simply give up on simrel.

**Comment by merks** [comment]
The status quo is fine.

@akurtakov  I hope you have a great vacation!  🍹
