### ISSUE TITLE
wikitext: {toc} not working

### ISSUE THREAD

**Issue by StefanLindner** [eclipse-mylyn/org.eclipse.mylyn.docs#127]
My general quetion: is the documentation site still upp to date for the current releases?
https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.mylyn.wikitext.help.ui%2Fhelp%2FTextile-Syntax.html

The `{toc}` extension ist not working at all.
It was not working for years but my issue at bugzilla was closed by the move to gibhub.

**Comment by merks** [comment]
I think these are the bundles involved in implementing that support:

https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs/tree/master/wikitext/core

**Comment by akurtakov** [comment]
No one has looked into textile support lately thus I highly encourage you to look into the issue itself if its important for you.

**Comment by akurtakov** [comment]
For the clarity of this issue - what was the problem and how did you fix it? Someone else might benefit from it at some point.
