### ISSUE TITLE
files with non lowercase extension not correctly opened

### ISSUE THREAD

**Issue by Bananeweizen** [eclipse-mylyn/org.eclipse.mylyn.docs#140]
readme.md is opened correctly in a markdown editor. README.MD is opened in a textile editor, because the uppercase extension is not correctly mapped to a language.

the language registry is normalized to lower case during initialization at https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs/blob/3c9a2de5881cea8ca0b780ecf3f9fe8c27bae534/wikitext/ui/org.eclipse.mylyn.wikitext.ui/src/org/eclipse/mylyn/internal/wikitext/ui/registry/WikiTextExtensionPointReader.java#L357 but the editor lookup doesn't do the same normalization: https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs/blob/3c9a2de5881cea8ca0b780ecf3f9fe8c27bae534/wikitext/ui/org.eclipse.mylyn.wikitext.ui/src/org/eclipse/mylyn/internal/wikitext/ui/registry/WikiTextExtensionPointReader.java#L178

**Comment by akurtakov** [comment]
If you provide a PR I'll push immediately.
