### ISSUE TITLE
Drop useless p2 sites from build

### ISSUE THREAD

**Issue by akurtakov** [eclipse-mylyn/org.eclipse.mylyn.docs#25]
The repo build at https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs/blob/master/docs/org.eclipse.mylyn.docs-site/category.xml contains what's in https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs/blob/master/wikitext/ui/org.eclipse.mylyn.wikitext-site/category.xml and https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs/blob/master/epub/ui/org.eclipse.mylyn.docs.epub-site/category.xml . Thus I would like to drop the later and have the single p2 repo org.eclipse.mylyn.docs-site . That would simplify build and speed up build esp considering pgp signing of deps not coming from Orbit for the future.

**Comment by akurtakov** [comment]
@leods wdyt?

**Comment by leods** [comment]
I'm guessing these can probably go away. There might have been separate releases for core Wikitext and Epub back in the day that I'm not aware of, but we haven't done that for some time. @turesheim do you feel there's still a need to maintain https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs/blob/master/epub/ui/org.eclipse.mylyn.docs.epub-site/category.xml still?

**Comment by akurtakov** [comment]
I proceed with this one.

**Comment by turesheim** [comment]
> I'm guessing these can probably go away. There might have been separate releases for core Wikitext and Epub back in the day that I'm not aware of, but we haven't done that for some time. @turesheim do you feel there's still a need to maintain https://github.com/eclipse-mylyn/org.eclipse.mylyn.docs/blob/master/epub/ui/org.eclipse.mylyn.docs.epub-site/category.xml still?

No, I think it's pretty safe to remove.
