### ISSUE TITLE
Latest updatesite not updated anymore

### ISSUE THREAD

**Issue by BeckerFrank** [eclipse-mylyn/org.eclipse.mylyn.docs#34]
https://download.eclipse.org/mylyn/docs/releases/3.0/ is not up to date 

This update site is now two releases behind the latest release. It contains 3.0.43 instead of 3.0.45.

This Issue was opened in Repository org.eclipse.mylyn instead of org.eclipse.mylyn.docs but is Mylyn Docs only.

See Issue https://github.com/eclipse-mylyn/org.eclipse.mylyn/issues/6

**Comment by leods** [comment]
This is corrected now with the 3.0.46 release.
