### ISSUE TITLE
Wiki Text Editor Does Not Have High Resolution Icons

### ISSUE THREAD

**Issue by BeckerWdf** [eclipse-mylyn/org.eclipse.mylyn.docs#78]
I editor icon for the wikitext editor looks blurry on 4k displays
<img width="165" alt="image" src="https://user-images.githubusercontent.com/28338612/231993198-78d012d1-b6d2-4647-b18b-2bfe546a6b83.png">

I could contribute high resolution icons fro this. Are you open for contributions?

**Comment by akurtakov** [comment]
Sure we are

**Comment by BeckerWdf** [comment]
> Sure we are

Here we go: #79
